# Understand *return_sequence* and *return_state* in Kera LSTM

In [51]:
import numpy as np
from keras.models import Model, Sequential
from keras.layers import Input, LSTM, Dense, TimeDistributed

In [5]:
data = np.array([.1, .2, .3]).reshape((1, 3, 1))

In [4]:
input1 = Input(shape=(3, 1))
output = LSTM(1)(input1)

model = Model(inputs=input1, outputs=output)

model.predict(data)

array([[0.12032839]], dtype=float32)

In [8]:
# return sequences
input1 = Input(shape=(3, 1))
output = LSTM(1, return_sequences=True)(input1)
model = Model(inputs=input1, outputs=output)
model.predict(data)

array([[[-0.00095629],
        [-0.00264443],
        [-0.00481701]]], dtype=float32)

In [10]:
# return state
# state_o is the output of the layer, state_c is the layer hidden state, lstm1 is also the output of the layer
input1 = Input(shape=(3, 1))
lstm1, state_o, state_c = LSTM(1, return_state=True)(input1)
model = Model(inputs=input1, outputs=[lstm1, state_o, state_c])
model.predict(data)

[array([[0.12683292]], dtype=float32),
 array([[0.12683292]], dtype=float32),
 array([[0.26003337]], dtype=float32)]

In [11]:
# return_state and return_sequence
input1 = Input(shape=(3, 1))
lstm1, state_o, state_c = LSTM(1, return_sequences=True, return_state=True)(input1)
model = Model(inputs=input1, outputs=[lstm1, state_o, state_c])
model.predict(data)

[array([[[-0.01053916],
         [-0.02721879],
         [-0.04768779]]], dtype=float32),
 array([[-0.04768779]], dtype=float32),
 array([[-0.10730134]], dtype=float32)]

return_sequence tell the LSTM layer to return a value for each time step so that, it can be pass to the next LSTM layer if required. When return_sequence=False, LSTM return only the value of the last time step.

return_state give access to the layer state which sometime differs from the output state

# Time serie preditction with LSTM

In [13]:
length = 5
seq = np.array([i/float(length) for i in range(length)])
seq

array([0. , 0.2, 0.4, 0.6, 0.8])

## One-to-One LSTM

In [18]:
X = seq.reshape((length, 1, 1))
y = seq.reshape((length, 1))
print(X, y, sep="\n----------\n")

[[[0. ]]

 [[0.2]]

 [[0.4]]

 [[0.6]]

 [[0.8]]]
----------
[[0. ]
 [0.2]
 [0.4]
 [0.6]
 [0.8]]


In [42]:
n_neurons = length
n_batch = length
n_epochs = 1000

In [35]:
model = Sequential()
model.add(LSTM(n_neurons, input_shape=(1, 1)))
model.add(Dense(1))
model.compile(loss="mse", optimizer="adam")
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_10 (LSTM)               (None, 5)                 140       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 6         
Total params: 146
Trainable params: 146
Non-trainable params: 0
_________________________________________________________________


In [36]:
model.fit(X, y, epochs=n_epochs, batch_size=n_batch, verbose=2)

Epoch 1/1000
 - 1s - loss: 0.3433
Epoch 2/1000
 - 0s - loss: 0.3408
Epoch 3/1000
 - 0s - loss: 0.3384
Epoch 4/1000
 - 0s - loss: 0.3361
Epoch 5/1000
 - 0s - loss: 0.3337
Epoch 6/1000
 - 0s - loss: 0.3313
Epoch 7/1000
 - 0s - loss: 0.3290
Epoch 8/1000
 - 0s - loss: 0.3267
Epoch 9/1000
 - 0s - loss: 0.3244
Epoch 10/1000
 - 0s - loss: 0.3221
Epoch 11/1000
 - 0s - loss: 0.3199
Epoch 12/1000
 - 0s - loss: 0.3176
Epoch 13/1000
 - 0s - loss: 0.3154
Epoch 14/1000
 - 0s - loss: 0.3132
Epoch 15/1000
 - 0s - loss: 0.3110
Epoch 16/1000
 - 0s - loss: 0.3088
Epoch 17/1000
 - 0s - loss: 0.3067
Epoch 18/1000
 - 0s - loss: 0.3045
Epoch 19/1000
 - 0s - loss: 0.3024
Epoch 20/1000
 - 0s - loss: 0.3003
Epoch 21/1000
 - 0s - loss: 0.2982
Epoch 22/1000
 - 0s - loss: 0.2961
Epoch 23/1000
 - 0s - loss: 0.2940
Epoch 24/1000
 - 0s - loss: 0.2919
Epoch 25/1000
 - 0s - loss: 0.2899
Epoch 26/1000
 - 0s - loss: 0.2879
Epoch 27/1000
 - 0s - loss: 0.2858
Epoch 28/1000
 - 0s - loss: 0.2838
Epoch 29/1000
 - 0s - loss: 0

Epoch 232/1000
 - 0s - loss: 0.0749
Epoch 233/1000
 - 0s - loss: 0.0746
Epoch 234/1000
 - 0s - loss: 0.0743
Epoch 235/1000
 - 0s - loss: 0.0740
Epoch 236/1000
 - 0s - loss: 0.0737
Epoch 237/1000
 - 0s - loss: 0.0734
Epoch 238/1000
 - 0s - loss: 0.0731
Epoch 239/1000
 - 0s - loss: 0.0728
Epoch 240/1000
 - 0s - loss: 0.0725
Epoch 241/1000
 - 0s - loss: 0.0723
Epoch 242/1000
 - 0s - loss: 0.0720
Epoch 243/1000
 - 0s - loss: 0.0717
Epoch 244/1000
 - 0s - loss: 0.0715
Epoch 245/1000
 - 0s - loss: 0.0712
Epoch 246/1000
 - 0s - loss: 0.0709
Epoch 247/1000
 - 0s - loss: 0.0707
Epoch 248/1000
 - 0s - loss: 0.0704
Epoch 249/1000
 - 0s - loss: 0.0702
Epoch 250/1000
 - 0s - loss: 0.0699
Epoch 251/1000
 - 0s - loss: 0.0697
Epoch 252/1000
 - 0s - loss: 0.0694
Epoch 253/1000
 - 0s - loss: 0.0692
Epoch 254/1000
 - 0s - loss: 0.0690
Epoch 255/1000
 - 0s - loss: 0.0687
Epoch 256/1000
 - 0s - loss: 0.0685
Epoch 257/1000
 - 0s - loss: 0.0683
Epoch 258/1000
 - 0s - loss: 0.0681
Epoch 259/1000
 - 0s - loss:

Epoch 460/1000
 - 0s - loss: 0.0423
Epoch 461/1000
 - 0s - loss: 0.0421
Epoch 462/1000
 - 0s - loss: 0.0420
Epoch 463/1000
 - 0s - loss: 0.0419
Epoch 464/1000
 - 0s - loss: 0.0418
Epoch 465/1000
 - 0s - loss: 0.0417
Epoch 466/1000
 - 0s - loss: 0.0416
Epoch 467/1000
 - 0s - loss: 0.0415
Epoch 468/1000
 - 0s - loss: 0.0413
Epoch 469/1000
 - 0s - loss: 0.0412
Epoch 470/1000
 - 0s - loss: 0.0411
Epoch 471/1000
 - 0s - loss: 0.0410
Epoch 472/1000
 - 0s - loss: 0.0409
Epoch 473/1000
 - 0s - loss: 0.0408
Epoch 474/1000
 - 0s - loss: 0.0407
Epoch 475/1000
 - 0s - loss: 0.0406
Epoch 476/1000
 - 0s - loss: 0.0404
Epoch 477/1000
 - 0s - loss: 0.0403
Epoch 478/1000
 - 0s - loss: 0.0402
Epoch 479/1000
 - 0s - loss: 0.0401
Epoch 480/1000
 - 0s - loss: 0.0400
Epoch 481/1000
 - 0s - loss: 0.0399
Epoch 482/1000
 - 0s - loss: 0.0398
Epoch 483/1000
 - 0s - loss: 0.0396
Epoch 484/1000
 - 0s - loss: 0.0395
Epoch 485/1000
 - 0s - loss: 0.0394
Epoch 486/1000
 - 0s - loss: 0.0393
Epoch 487/1000
 - 0s - loss:

Epoch 688/1000
 - 0s - loss: 0.0171
Epoch 689/1000
 - 0s - loss: 0.0170
Epoch 690/1000
 - 0s - loss: 0.0169
Epoch 691/1000
 - 0s - loss: 0.0168
Epoch 692/1000
 - 0s - loss: 0.0167
Epoch 693/1000
 - 0s - loss: 0.0166
Epoch 694/1000
 - 0s - loss: 0.0165
Epoch 695/1000
 - 0s - loss: 0.0164
Epoch 696/1000
 - 0s - loss: 0.0163
Epoch 697/1000
 - 0s - loss: 0.0162
Epoch 698/1000
 - 0s - loss: 0.0161
Epoch 699/1000
 - 0s - loss: 0.0160
Epoch 700/1000
 - 0s - loss: 0.0159
Epoch 701/1000
 - 0s - loss: 0.0158
Epoch 702/1000
 - 0s - loss: 0.0157
Epoch 703/1000
 - 0s - loss: 0.0156
Epoch 704/1000
 - 0s - loss: 0.0155
Epoch 705/1000
 - 0s - loss: 0.0155
Epoch 706/1000
 - 0s - loss: 0.0154
Epoch 707/1000
 - 0s - loss: 0.0153
Epoch 708/1000
 - 0s - loss: 0.0152
Epoch 709/1000
 - 0s - loss: 0.0151
Epoch 710/1000
 - 0s - loss: 0.0150
Epoch 711/1000
 - 0s - loss: 0.0149
Epoch 712/1000
 - 0s - loss: 0.0148
Epoch 713/1000
 - 0s - loss: 0.0147
Epoch 714/1000
 - 0s - loss: 0.0146
Epoch 715/1000
 - 0s - loss:

Epoch 916/1000
 - 0s - loss: 0.0026
Epoch 917/1000
 - 0s - loss: 0.0026
Epoch 918/1000
 - 0s - loss: 0.0025
Epoch 919/1000
 - 0s - loss: 0.0025
Epoch 920/1000
 - 0s - loss: 0.0025
Epoch 921/1000
 - 0s - loss: 0.0025
Epoch 922/1000
 - 0s - loss: 0.0024
Epoch 923/1000
 - 0s - loss: 0.0024
Epoch 924/1000
 - 0s - loss: 0.0024
Epoch 925/1000
 - 0s - loss: 0.0024
Epoch 926/1000
 - 0s - loss: 0.0023
Epoch 927/1000
 - 0s - loss: 0.0023
Epoch 928/1000
 - 0s - loss: 0.0023
Epoch 929/1000
 - 0s - loss: 0.0023
Epoch 930/1000
 - 0s - loss: 0.0022
Epoch 931/1000
 - 0s - loss: 0.0022
Epoch 932/1000
 - 0s - loss: 0.0022
Epoch 933/1000
 - 0s - loss: 0.0022
Epoch 934/1000
 - 0s - loss: 0.0021
Epoch 935/1000
 - 0s - loss: 0.0021
Epoch 936/1000
 - 0s - loss: 0.0021
Epoch 937/1000
 - 0s - loss: 0.0021
Epoch 938/1000
 - 0s - loss: 0.0021
Epoch 939/1000
 - 0s - loss: 0.0020
Epoch 940/1000
 - 0s - loss: 0.0020
Epoch 941/1000
 - 0s - loss: 0.0020
Epoch 942/1000
 - 0s - loss: 0.0020
Epoch 943/1000
 - 0s - loss:

In [38]:
results = model.predict(X, batch_size=n_batch, verbose=0)
for v in results:
    print(f"{np.round(v, 1)}")

[0.1]
[0.2]
[0.4]
[0.6]
[0.8]


## Many-to-One LSTM for sequence prediction

In [40]:
X = seq.reshape((1, length, 1))
y = seq.reshape(1, 5)
print(X, y, sep="\n-------------\n")

[[[0. ]
  [0.2]
  [0.4]
  [0.6]
  [0.8]]]
-------------
[[0.  0.2 0.4 0.6 0.8]]


In [45]:
model2 = Sequential()
model2.add(LSTM(n_neurons, input_shape=(length, 1)))
model2.add(Dense(length))
model2.compile(loss="mean_squared_error", optimizer="adam")
model2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_12 (LSTM)               (None, 5)                 140       
_________________________________________________________________
dense_5 (Dense)              (None, 5)                 30        
Total params: 170
Trainable params: 170
Non-trainable params: 0
_________________________________________________________________


In [46]:
model2.fit(X, y, epochs=500, batch_size=1, verbose=1)

Epoch 1/500
1/1 [==============================] - 1s 774ms/step - loss: 0.2838
Epoch 2/500
1/1 [==============================] - 0s 4ms/step - loss: 0.2806
Epoch 3/500
1/1 [==============================] - 0s 5ms/step - loss: 0.2775
Epoch 4/500
1/1 [==============================] - 0s 5ms/step - loss: 0.2744
Epoch 5/500
1/1 [==============================] - 0s 5ms/step - loss: 0.2714
Epoch 6/500
1/1 [==============================] - 0s 10ms/step - loss: 0.2685
Epoch 7/500
1/1 [==============================] - 0s 8ms/step - loss: 0.2655
Epoch 8/500
1/1 [==============================] - 0s 5ms/step - loss: 0.2625
Epoch 9/500
1/1 [==============================] - 0s 7ms/step - loss: 0.2595
Epoch 10/500
1/1 [==============================] - 0s 11ms/step - loss: 0.2566
Epoch 11/500
1/1 [==============================] - 0s 12ms/step - loss: 0.2537
Epoch 12/500
1/1 [==============================] - 0s 8ms/step - loss: 0.2508
Epoch 13/500
1/1 [==============================] - 0s 8

Epoch 105/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0499
Epoch 106/500
1/1 [==============================] - 0s 7ms/step - loss: 0.0484
Epoch 107/500
1/1 [==============================] - 0s 6ms/step - loss: 0.0469
Epoch 108/500
1/1 [==============================] - 0s 6ms/step - loss: 0.0454
Epoch 109/500
1/1 [==============================] - 0s 6ms/step - loss: 0.0439
Epoch 110/500
1/1 [==============================] - 0s 5ms/step - loss: 0.0425
Epoch 111/500
1/1 [==============================] - 0s 12ms/step - loss: 0.0410
Epoch 112/500
1/1 [==============================] - 0s 12ms/step - loss: 0.0396
Epoch 113/500
1/1 [==============================] - 0s 6ms/step - loss: 0.0383
Epoch 114/500
1/1 [==============================] - 0s 11ms/step - loss: 0.0369
Epoch 115/500
1/1 [==============================] - 0s 5ms/step - loss: 0.0356
Epoch 116/500
1/1 [==============================] - 0s 14ms/step - loss: 0.0343
Epoch 117/500
1/1 [=================

Epoch 207/500
1/1 [==============================] - 0s 5ms/step - loss: 7.8532e-04
Epoch 208/500
1/1 [==============================] - 0s 10ms/step - loss: 7.5270e-04
Epoch 209/500
1/1 [==============================] - 0s 10ms/step - loss: 7.2130e-04
Epoch 210/500
1/1 [==============================] - 0s 5ms/step - loss: 6.9108e-04
Epoch 211/500
1/1 [==============================] - 0s 9ms/step - loss: 6.6201e-04
Epoch 212/500
1/1 [==============================] - 0s 7ms/step - loss: 6.3404e-04
Epoch 213/500
1/1 [==============================] - 0s 8ms/step - loss: 6.0716e-04
Epoch 214/500
1/1 [==============================] - 0s 7ms/step - loss: 5.8131e-04
Epoch 215/500
1/1 [==============================] - 0s 10ms/step - loss: 5.5646e-04
Epoch 216/500
1/1 [==============================] - 0s 6ms/step - loss: 5.3259e-04
Epoch 217/500
1/1 [==============================] - 0s 10ms/step - loss: 5.0965e-04
Epoch 218/500
1/1 [==============================] - 0s 7ms/step - loss:

1/1 [==============================] - 0s 11ms/step - loss: 5.7377e-06
Epoch 305/500
1/1 [==============================] - 0s 5ms/step - loss: 5.4060e-06
Epoch 306/500
1/1 [==============================] - 0s 5ms/step - loss: 5.0931e-06
Epoch 307/500
1/1 [==============================] - 0s 12ms/step - loss: 4.7972e-06
Epoch 308/500
1/1 [==============================] - 0s 7ms/step - loss: 4.5173e-06
Epoch 309/500
1/1 [==============================] - 0s 14ms/step - loss: 4.2533e-06
Epoch 310/500
1/1 [==============================] - 0s 10ms/step - loss: 4.0041e-06
Epoch 311/500
1/1 [==============================] - 0s 9ms/step - loss: 3.7687e-06
Epoch 312/500
1/1 [==============================] - 0s 10ms/step - loss: 3.5464e-06
Epoch 313/500
1/1 [==============================] - 0s 7ms/step - loss: 3.3366e-06
Epoch 314/500
1/1 [==============================] - 0s 15ms/step - loss: 3.1385e-06
Epoch 315/500
1/1 [==============================] - 0s 5ms/step - loss: 2.9517e-06


Epoch 402/500
1/1 [==============================] - 0s 6ms/step - loss: 6.3213e-09
Epoch 403/500
1/1 [==============================] - 0s 6ms/step - loss: 5.8251e-09
Epoch 404/500
1/1 [==============================] - 0s 4ms/step - loss: 5.3697e-09
Epoch 405/500
1/1 [==============================] - 0s 12ms/step - loss: 4.9565e-09
Epoch 406/500
1/1 [==============================] - 0s 11ms/step - loss: 4.5593e-09
Epoch 407/500
1/1 [==============================] - 0s 4ms/step - loss: 4.2010e-09
Epoch 408/500
1/1 [==============================] - 0s 7ms/step - loss: 3.8692e-09
Epoch 409/500
1/1 [==============================] - 0s 6ms/step - loss: 3.5635e-09
Epoch 410/500
1/1 [==============================] - 0s 6ms/step - loss: 3.2772e-09
Epoch 411/500
1/1 [==============================] - 0s 7ms/step - loss: 3.0173e-09
Epoch 412/500
1/1 [==============================] - 0s 5ms/step - loss: 2.7753e-09
Epoch 413/500
1/1 [==============================] - 0s 10ms/step - loss: 

1/1 [==============================] - 0s 5ms/step - loss: 5.1240e-13
Epoch 500/500
1/1 [==============================] - 0s 5ms/step - loss: 4.8438e-13


In [49]:
result = model2.predict(X, batch_size=1)
for v in result[0:length]:
    print(np.round(v, 1))

[0.  0.2 0.4 0.6 0.8]


## Many-to-Many LSTM for sequence prediction

In [50]:
y = seq.reshape((1, length, 1))
y

array([[[0. ],
        [0.2],
        [0.4],
        [0.6],
        [0.8]]])

In [54]:
model3 = Sequential()
model3.add(LSTM(length, input_shape = (length, 1), return_sequences=True))
model3.add(TimeDistributed(Dense(1)))
model3.compile(loss="mean_squared_error", optimizer="adam")
model3.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_13 (LSTM)               (None, 5, 5)              140       
_________________________________________________________________
time_distributed_1 (TimeDist (None, 5, 1)              6         
Total params: 146
Trainable params: 146
Non-trainable params: 0
_________________________________________________________________


In [55]:
n_epochs = 500
model3.fit(X, y, epochs=n_epochs, batch_size=1, verbose=2)

Epoch 1/500
 - 1s - loss: 0.2508
Epoch 2/500
 - 0s - loss: 0.2468
Epoch 3/500
 - 0s - loss: 0.2429
Epoch 4/500
 - 0s - loss: 0.2389
Epoch 5/500
 - 0s - loss: 0.2350
Epoch 6/500
 - 0s - loss: 0.2312
Epoch 7/500
 - 0s - loss: 0.2274
Epoch 8/500
 - 0s - loss: 0.2236
Epoch 9/500
 - 0s - loss: 0.2198
Epoch 10/500
 - 0s - loss: 0.2162
Epoch 11/500
 - 0s - loss: 0.2125
Epoch 12/500
 - 0s - loss: 0.2089
Epoch 13/500
 - 0s - loss: 0.2053
Epoch 14/500
 - 0s - loss: 0.2018
Epoch 15/500
 - 0s - loss: 0.1983
Epoch 16/500
 - 0s - loss: 0.1949
Epoch 17/500
 - 0s - loss: 0.1915
Epoch 18/500
 - 0s - loss: 0.1881
Epoch 19/500
 - 0s - loss: 0.1848
Epoch 20/500
 - 0s - loss: 0.1816
Epoch 21/500
 - 0s - loss: 0.1783
Epoch 22/500
 - 0s - loss: 0.1751
Epoch 23/500
 - 0s - loss: 0.1720
Epoch 24/500
 - 0s - loss: 0.1689
Epoch 25/500
 - 0s - loss: 0.1658
Epoch 26/500
 - 0s - loss: 0.1628
Epoch 27/500
 - 0s - loss: 0.1598
Epoch 28/500
 - 0s - loss: 0.1568
Epoch 29/500
 - 0s - loss: 0.1539
Epoch 30/500
 - 0s - lo

 - 0s - loss: 0.0057
Epoch 239/500
 - 0s - loss: 0.0056
Epoch 240/500
 - 0s - loss: 0.0056
Epoch 241/500
 - 0s - loss: 0.0056
Epoch 242/500
 - 0s - loss: 0.0055
Epoch 243/500
 - 0s - loss: 0.0055
Epoch 244/500
 - 0s - loss: 0.0055
Epoch 245/500
 - 0s - loss: 0.0054
Epoch 246/500
 - 0s - loss: 0.0054
Epoch 247/500
 - 0s - loss: 0.0054
Epoch 248/500
 - 0s - loss: 0.0054
Epoch 249/500
 - 0s - loss: 0.0053
Epoch 250/500
 - 0s - loss: 0.0053
Epoch 251/500
 - 0s - loss: 0.0053
Epoch 252/500
 - 0s - loss: 0.0052
Epoch 253/500
 - 0s - loss: 0.0052
Epoch 254/500
 - 0s - loss: 0.0052
Epoch 255/500
 - 0s - loss: 0.0051
Epoch 256/500
 - 0s - loss: 0.0051
Epoch 257/500
 - 0s - loss: 0.0051
Epoch 258/500
 - 0s - loss: 0.0051
Epoch 259/500
 - 0s - loss: 0.0050
Epoch 260/500
 - 0s - loss: 0.0050
Epoch 261/500
 - 0s - loss: 0.0050
Epoch 262/500
 - 0s - loss: 0.0049
Epoch 263/500
 - 0s - loss: 0.0049
Epoch 264/500
 - 0s - loss: 0.0049
Epoch 265/500
 - 0s - loss: 0.0049
Epoch 266/500
 - 0s - loss: 0.0048

Epoch 473/500
 - 0s - loss: 0.0022
Epoch 474/500
 - 0s - loss: 0.0022
Epoch 475/500
 - 0s - loss: 0.0022
Epoch 476/500
 - 0s - loss: 0.0022
Epoch 477/500
 - 0s - loss: 0.0022
Epoch 478/500
 - 0s - loss: 0.0021
Epoch 479/500
 - 0s - loss: 0.0021
Epoch 480/500
 - 0s - loss: 0.0021
Epoch 481/500
 - 0s - loss: 0.0021
Epoch 482/500
 - 0s - loss: 0.0021
Epoch 483/500
 - 0s - loss: 0.0021
Epoch 484/500
 - 0s - loss: 0.0021
Epoch 485/500
 - 0s - loss: 0.0021
Epoch 486/500
 - 0s - loss: 0.0021
Epoch 487/500
 - 0s - loss: 0.0021
Epoch 488/500
 - 0s - loss: 0.0021
Epoch 489/500
 - 0s - loss: 0.0021
Epoch 490/500
 - 0s - loss: 0.0021
Epoch 491/500
 - 0s - loss: 0.0021
Epoch 492/500
 - 0s - loss: 0.0021
Epoch 493/500
 - 0s - loss: 0.0021
Epoch 494/500
 - 0s - loss: 0.0021
Epoch 495/500
 - 0s - loss: 0.0021
Epoch 496/500
 - 0s - loss: 0.0021
Epoch 497/500
 - 0s - loss: 0.0021
Epoch 498/500
 - 0s - loss: 0.0021
Epoch 499/500
 - 0s - loss: 0.0021
Epoch 500/500
 - 0s - loss: 0.0020


In [58]:
result = model3.predict(X, batch_size=1)
for v in result[0,:,0]:
    print(round(v, 1))

0.1
0.2
0.4
0.6
0.8
